name: mvn clean package
on: 
    push:
        branches:
            - "main"

jobs: 
    cleanup-mvn-package: 
        name: cleanupmvn package
        runs-on: ubuntu-latest
        steps: 
            - name: checkout
              uses: actions/checkout@v4

            - name: mvn clean
              run: mnv clean package
              shell: bash



